### ISSUE TITLE
Errors should be rejected instead of thrown

### ISSUE THREAD

**Issue by Radiergummi** [adius/epub-metadata#1]
I'm using epub-metadata to automatically read and parse metadata from epub files before uploading them into a library (kind of a Calibre clone..). While testing with a lot of different epub books, I noticed on several occasions that epub-metadata throws errors instead of cleanly rejecting the promise, which leads to code failure.  
This should be solved to make output predictable.

````
TypeError: Cannot read property 'toLowerCase' of undefined
    at /node_modules/epub-metadata/source/index.js:97:31
    at Array.forEach (native)
    at /node_modules/epub-metadata/source/index.js:96:24
    at tryCallOne (/node_modules/promise/lib/core.js:37:12)
````

**Comment by ad-si** [comment]
Thanks for the heads up! Fixed it in 3779ce3.
